### ISSUE TITLE
Add Slack Channel Invite Link

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [Marauders-9998/Marauders-Website#22]
Marauders need more developers and for constant communication, we need more people to be aware of the communication channel.

Add the Slack Channel invite link of Marauders on the Website.

The slack channel invite link can be obtained from the Slack Badge in README.

**Comment by ivaibhavjindal** [comment]
@Vibhu-Agarwal I'd like to work on this. Can you assign this to me?

**Comment by Vibhu-Agarwal** [comment]
Sure @ivaibhavjindal
